// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/base/background.vue')['default']
    ChangePassword: typeof import('./src/components/dialogs/changePassword.vue')['default']
    ChangePhone: typeof import('./src/components/dialogs/changePhone.vue')['default']
    ChangeUsername: typeof import('./src/components/dialogs/changeUsername.vue')['default']
    DoubleColCard: typeof import('./src/components/doubleColCard.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Footer: typeof import('./src/components/base/footer.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    Header: typeof import('./src/components/base/header.vue')['default']
    LoginForm: typeof import('./src/components/loginForm.vue')['default']
    ProductsListView: typeof import('./src/components/ProductsListView.vue')['default']
    ValidatePhone: typeof import('./src/components/dialogs/validatePhone.vue')['default']
  }
}

export { }
